name = "Caching"
uuid = "68ad905a-5087-500a-aae7-0fd6acda2eb1"
authors = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.2.1"

[deps]
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
CodecLz4 = "5ba52731-8f18-5e0d-9241-30f10d1ec561"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CodecBzip2 = "^0.7"
CodecLz4 = "^0.4"
CodecZlib = "^0.7"
DataStructures = "^0"
MacroTools = "^0.5"
TranscodingStreams = "^0.9.3"
julia = "1.8"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging"]
